version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 20
  reviewers:
  - mjclawar
  ignore:
  - dependency-name: dask[complete]
    versions:
    - 2021.1.1
    - 2021.4.0
  - dependency-name: dask
    versions:
    - 2021.1.1
    - 2021.3.0
  - dependency-name: numpy
    versions:
    - 1.20.0
